name: Verify APP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

  steps:
    - uses: actions/checkout@v2
    - name: Setup Node
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
        cache: "yarn"
    - name: Intalling dependencies
    - run: yarn install
    - name: Running lint
    - run: yarn lint
    - name: Running typecheck
    - run: yarn typecheck
    - name: Running tests
    - run: yarn test
